!!brut.androlib.meta.MetaInfo
apkFileName: com.microsoft.skydrive.apk
compressionType: false
doNotCompress:
- arsc
isFrameworkApk: false
packageInfo:
  forcedPackageId: '127'
  renameManifestPackage: null
sdkInfo:
  minSdkVersion: '19'
  targetSdkVersion: '24'
sharedLibrary: false
unknownFiles:
  build-data.properties: '8'
  com/microsoft/powerlift/acompli_cacerts.bks: '8'
  fabric/com.crashlytics.sdk.android.answers.properties: '8'
  fabric/com.crashlytics.sdk.android.beta.properties: '8'
  fabric/com.crashlytics.sdk.android.crashlytics-core.properties: '8'
  fabric/com.crashlytics.sdk.android.crashlytics-ndk.properties: '8'
  fabric/com.crashlytics.sdk.android.crashlytics.properties: '8'
  fabric/io.fabric.sdk.android.fabric.properties: '8'
  jsr305_annotations/Jsr305_annotations.gwt.xml: '8'
usesFramework:
  ids:
  - 1
  tag: null
version: 2.2.2
versionInfo:
  versionCode: '1920044931'
  versionName: '4.12'
