!!brut.androlib.meta.MetaInfo
apkFileName: com.google.android.webview.apk
compressionType: false
doNotCompress:
- arsc
- pak
- dat
- bin
isFrameworkApk: true
packageInfo:
  forcedPackageId: '2'
  renameManifestPackage: null
sdkInfo:
  minSdkVersion: '21'
  targetSdkVersion: '25'
sharedLibrary: true
unknownFiles: {}
usesFramework:
  ids:
  - 1
  tag: null
version: 2.2.2
versionInfo:
  versionCode: '302908300'
  versionName: 58.0.3029.83
