!!brut.androlib.meta.MetaInfo
apkFileName: com.rsupport.rs.activity.rsupport.aas2.apk
compressionType: false
doNotCompress:
- arsc
isFrameworkApk: false
packageInfo:
  forcedPackageId: '127'
  renameManifestPackage: null
sdkInfo:
  minSdkVersion: '8'
  targetSdkVersion: '23'
sharedLibrary: false
unknownFiles: {}
usesFramework:
  ids:
  - 1
  tag: null
version: 2.2.2
versionInfo:
  versionCode: '153'
  versionName: 1.5 (build 153)
