!!brut.androlib.meta.MetaInfo
apkFileName: com.naranya.claroapps.apk
compressionType: false
doNotCompress:
- arsc
isFrameworkApk: false
packageInfo:
  forcedPackageId: '127'
  renameManifestPackage: null
sdkInfo:
  minSdkVersion: '10'
  targetSdkVersion: '23'
sharedLibrary: false
unknownFiles:
  build-data.properties: '8'
  jsr305_annotations/Jsr305_annotations.gwt.xml: '8'
  com/smartadserver/android/library/mediation/SASMotionleadAdapter.jav: '8'
usesFramework:
  ids:
  - 1
  tag: null
version: 2.2.2
versionInfo:
  versionCode: '40'
  versionName: 2.1.0
