!!brut.androlib.meta.MetaInfo
apkFileName: com.sec.android.app.voicenote.apk
compressionType: false
doNotCompress:
- arsc
isFrameworkApk: false
packageInfo:
  forcedPackageId: '127'
  renameManifestPackage: null
sdkInfo:
  minSdkVersion: '23'
  targetSdkVersion: '23'
sharedLibrary: false
unknownFiles:
  isoparser-default.properties: '8'
  version.txt: '8'
  SEC-INF/buildConfirm.crt: '8'
  SEC-INF/buildinfo.xml: '8'
usesFramework:
  ids:
  - 1
  tag: null
version: 2.2.2
versionInfo:
  versionCode: '2018317000'
  versionName: 20.1.83-17
